name: Build Windows

on: [push, pull_request]

jobs:
  build:
  # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: vcpkg
      run: vcpkg install

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.3.1
      with:
        version: 6.10.1
        modules: 'qtshadertools qtquick3d'
        
    - name: Configure CMake
      run: >
        cmake -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg/scripts/buildsystems/vcpkg.cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config Release
