name: Build Ubuntu

on: [push, pull_request]

jobs:
  build:
  # hhttps://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: apt update
      run: sudo apt-get update

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qt6-base-dev \
          qt6-base-private-dev \
          qt6-base-dev-tools \
          qt6-shadertools-dev \
          libqt6shadertools6 \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libxkbcommon-dev \
          libvulkan-dev \
          vulkan-tools \
          vulkan-utility-libraries-dev \
          vulkan-validationlayers

    - name: Install SDL3
      uses: libsdl-org/setup-sdl@main
      with:
        install-linux-dependencies: true
        version: 3-latest
        version-sdl-image: 3-latest

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config Release
